install.packages("magrittr")
install.packages("splitstackshape")
install.packages("data.table")
install.packages("tidyverse")
install.packages("ggforce")
install.packages("ggthemes")
install.packages("heatmaply")
install.packages("DT")
install.packages("crosstalk")
install.packages("htmltools")
install.packages("argparse")
install.packages("viridis")
devtools::install_version('rmarkdown', version='2.19', force = TRUE)
devtools::install_version('dplyr', version='1.0.10', force = TRUE)