install.packages("magrittr")
install.packages("data.table")
install.packages("tidyverse")
install.packages("ggthemes")
install.packages("ggrepel")
install.packages("mousetrap")
install.packages("uwot")
install.packages("ggExtra")