FROM cmap/base-clue-mts:latest
MAINTAINER Andrew Boghossian <cmap-soft@broadinstitute.org>
LABEL clue.mts.pipeline.clue.io.version="0.0.1"
LABEL clue.mts.pipeline.clue.io.vendor="PRISM"

COPY ./src/MTS_functions.R /src/MTS_functions.R
COPY ./MTS_Data_Processing.R /MTS_Data_Processing.R

ENTRYPOINT ["Rscript", "MTS_Data_Processing.R"]


