options(repos=structure(c(CRAN="http://cran.r-project.org")))

install.packages("tidyverse")
install.packages("hdf5r")
install.packages("reshape2")
install.packages("readr")
install.packages("magrittr")
install.packages("dr4pl") ## for DRC curve fit
install.packages("drc") ## for DRC curve fit
install.packages("data.table")
install.packages("scam")
install.packages("argparse")
install.packages("splitstackshape")
install.packages("R.utils")
install.packages("BiocManager")
BiocManager::install()
BiocManager::install("sva")
BiocManager::install("limma", ask = FALSE)
install.packages("PRROC")
install.packages("gmodels")
install.packages("R.utils")
install.packages("devtools")
devtools::install_github("broadinstitute/cdsr_models", dependencies=TRUE, force=TRUE)
