options(repos=structure(c(CRAN="http://cran.r-project.org")))

install.packages("tidyverse")
install.packages("hdf5r")
install.packages("reshape2")
install.packages("readr")
install.packages("magrittr")
install.packages("dr4pl")
install.packages("data.table")
install.packages("scam")
install.packages("BiocManager")
BiocManager::install()
BiocManager::install("sva")
install.packages("PRROC")
install.packages("gmodels")
